"""
PyTorch reference for decoder-only LM (decoder_lm).

Matches dnn.c's decoder_lm_forward exactly:
  embed → N × transformer_block → norm → lm_head

Usage:
    uv run --with torch python test/ref_decoder_lm.py
    uv run --with torch python test/ref_decoder_lm.py --small   # tiny config
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import sys

SMALL = '--small' in sys.argv
SEED = 42

if SMALL:
    B, N, vocab_size, d_model, n_layers, n_heads, intermediate = \
        1, 3, 10, 4, 2, 2, 8
else:
    B, N, vocab_size, d_model, n_layers, n_heads, intermediate = \
        2, 4, 16, 8, 3, 2, 16

d_k = d_model // n_heads
assert d_model == n_heads * d_k

torch.manual_seed(SEED)

# ── Model components ──

class SwiGLUFFN(nn.Module):
    def __init__(self, d_model, intermediate):
        super().__init__()
        self.gate_proj = nn.Linear(d_model, intermediate, bias=True)
        self.up_proj   = nn.Linear(d_model, intermediate, bias=True)
        self.down_proj = nn.Linear(intermediate, d_model, bias=True)

    def forward(self, x):
        gate = self.gate_proj(x)
        up   = self.up_proj(x)
        hidden = F.silu(gate) * up
        return self.down_proj(hidden)


class TransformerBlock(nn.Module):
    def __init__(self, d_model, n_heads, d_k, intermediate):
        super().__init__()
        self.n_heads = n_heads
        self.d_k = d_k
        self.d_model = d_model

        self.attn_norm = nn.LayerNorm(d_model, elementwise_affine=True)
        self.ffn_norm  = nn.LayerNorm(d_model, elementwise_affine=True)

        self.q_proj   = nn.Linear(d_model, n_heads * d_k, bias=True)
        self.k_proj   = nn.Linear(d_model, n_heads * d_k, bias=True)
        self.v_proj   = nn.Linear(d_model, n_heads * d_k, bias=True)
        self.out_proj = nn.Linear(n_heads * d_k, d_model, bias=True)

        self.ffn = SwiGLUFFN(d_model, intermediate)

    def forward(self, x):
        residual = x
        h = self.attn_norm(x)

        Q = self.q_proj(h)
        K = self.k_proj(h)
        V = self.v_proj(h)

        B, N, _ = Q.shape
        Q = Q.view(B, N, self.n_heads, self.d_k).transpose(1, 2)
        K = K.view(B, N, self.n_heads, self.d_k).transpose(1, 2)
        V = V.view(B, N, self.n_heads, self.d_k).transpose(1, 2)

        scale = 1.0 / math.sqrt(self.d_k)
        scores = torch.matmul(Q, K.transpose(-2, -1)) * scale

        mask = torch.triu(torch.full((N, N), float('-inf'), device=x.device), diagonal=1)
        scores = scores + mask

        P = F.softmax(scores, dim=-1)
        attn_out = torch.matmul(P, V)

        attn_out = attn_out.transpose(1, 2).contiguous().view(B, N, -1)
        attn_out = self.out_proj(attn_out)
        x = residual + attn_out

        residual = x
        h = self.ffn_norm(x)
        h = self.ffn(h)
        x = residual + h
        return x


class DecoderLM(nn.Module):
    """Match dnn.c decoder_lm: embed → N×block → norm → lm_head"""

    def __init__(self, vocab_size, d_model, n_layers, n_heads, d_k, intermediate):
        super().__init__()
        self.d_model = d_model
        self.vocab_size = vocab_size

        self.embedding = nn.Embedding(vocab_size, d_model)
        self.blocks = nn.ModuleList([
            TransformerBlock(d_model, n_heads, d_k, intermediate)
            for _ in range(n_layers)
        ])
        self.norm = nn.LayerNorm(d_model, elementwise_affine=True)
        self.lm_head = nn.Linear(d_model, vocab_size, bias=True)

    def forward(self, input_ids):
        h = self.embedding(input_ids)  # [B, N, d_model]
        for block in self.blocks:
            h = block(h)
        h = self.norm(h)
        logits = self.lm_head(h)  # [B, N, vocab_size]
        return logits


# ── Instantiate ──
model = DecoderLM(vocab_size, d_model, n_layers, n_heads, d_k, intermediate)
model.train()

# Input tokens: [B, N] int
input_ids = torch.randint(0, vocab_size, (B, N))
input_ids.requires_grad_(False)  # integers, no grad

logits = model(input_ids)

# Loss: summed logits (matches dnn_backward pattern of sum)
loss = logits.sum()
loss.backward()

def fmt_tensor(name, t):
    flat = t.detach().cpu().numpy().flatten()
    vals = ', '.join(f'{v:.10f}f' for v in flat)
    return f'    float {name.replace(".","_")}[] = {{{vals}}};\n'

def fmt_ints(name, t):
    flat = t.detach().cpu().numpy().flatten().astype(int)
    vals = ', '.join(str(v) for v in flat)
    return f'    int {name.replace(".","_")}[] = {{{vals}}};\n'

def fmt_shape(name, t):
    shape = list(t.shape)
    vals = ', '.join(str(s) for s in shape)
    return f'    int {name.replace(".","_")}_shape[] = {{{vals}}};\n\n'

def count_params(m):
    return sum(p.numel() for p in m.parameters())

print(f"/* Autogenerated by test/ref_decoder_lm.py", file=sys.stderr)
print(f"   seed={SEED}, config: B={B}, N={N}, vocab={vocab_size}, d_model={d_model},", file=sys.stderr)
print(f"   n_layers={n_layers}, n_heads={n_heads}, d_k={d_k}, intermediate={intermediate}", file=sys.stderr)
print(f"   total_params={count_params(model)} */", file=sys.stderr)

print(f"/* Config: B={B}, N={N}, vocab={vocab_size}, d_model={d_model},")
print(f"   n_layers={n_layers}, n_heads={n_heads}, d_k={d_k}, intermediate={intermediate} */")
print()

# Input IDs
print(fmt_ints('input_ids', input_ids))

# Output logits (forward)
print(fmt_tensor('logits', logits))

# Input gradient to embedding
print(fmt_tensor('grad_embedding_weight', model.embedding.weight.grad))

# Gradients for block 0 norms
print(fmt_tensor('grad_block0_attn_norm_weight', model.blocks[0].attn_norm.weight.grad))
print(fmt_tensor('grad_block0_attn_norm_bias', model.blocks[0].attn_norm.bias.grad))
print(fmt_tensor('grad_block0_ffn_norm_weight', model.blocks[0].ffn_norm.weight.grad))
print(fmt_tensor('grad_block0_ffn_norm_bias', model.blocks[0].ffn_norm.bias.grad))

# Gradients for block 0 q_proj
print(fmt_tensor('grad_block0_q_proj_weight', model.blocks[0].q_proj.weight.grad))
print(fmt_tensor('grad_block0_q_proj_bias', model.blocks[0].q_proj.bias.grad))

# Gradients for block 0 gate_proj
print(fmt_tensor('grad_block0_gate_proj_weight', model.blocks[0].ffn.gate_proj.weight.grad))
print(fmt_tensor('grad_block0_gate_proj_bias', model.blocks[0].ffn.gate_proj.bias.grad))

# Gradients for final norm
print(fmt_tensor('grad_norm_weight', model.norm.weight.grad))
print(fmt_tensor('grad_norm_bias', model.norm.bias.grad))

# Gradient for lm_head
print(fmt_tensor('grad_lm_head_weight', model.lm_head.weight.grad))
print(fmt_tensor('grad_lm_head_bias', model.lm_head.bias.grad))

# If multi-layer, spot-check block 1 as well
if n_layers > 1:
    print(fmt_tensor('grad_block1_attn_norm_weight', model.blocks[1].attn_norm.weight.grad))
    print(fmt_tensor('grad_block1_attn_norm_bias', model.blocks[1].attn_norm.bias.grad))
    print(fmt_tensor('grad_block1_q_proj_weight', model.blocks[1].q_proj.weight.grad))
    print(fmt_tensor('grad_block1_q_proj_bias', model.blocks[1].q_proj.bias.grad))

if n_layers > 2:
    print(fmt_tensor('grad_block2_attn_norm_weight', model.blocks[2].attn_norm.weight.grad))
    print(fmt_tensor('grad_block2_attn_norm_bias', model.blocks[2].attn_norm.bias.grad))

print(file=sys.stderr)
print("// Done.  C-copy the printed arrays into test_decoder_lm.c", file=sys.stderr)
