"""
PyTorch reference for transformer_block.

Creates a single decoder-only transformer block (pre-norm causal attn + pre-norm SwiGLU FFN),
matching dnn.c's transformer_block_forward exactly.

Usage:
    uv run --with torch python test/ref_transformer.py
    uv run --with torch python test/ref_transformer.py --small   # smaller test config
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import sys

# ── Config ──
SMALL = '--small' in sys.argv

if SMALL:
    B, N, d_model, n_heads, intermediate = 1, 3, 4, 2, 8
else:
    B, N, d_model, n_heads, intermediate = 2, 4, 8, 2, 16

d_k = d_model // n_heads
assert d_model == n_heads * d_k

torch.manual_seed(42)

# ── Build block ──
class SwiGLUFFN(nn.Module):
    def __init__(self, d_model, intermediate):
        super().__init__()
        self.gate_proj = nn.Linear(d_model, intermediate, bias=True)
        self.up_proj   = nn.Linear(d_model, intermediate, bias=True)
        self.down_proj = nn.Linear(intermediate, d_model, bias=True)

    def forward(self, x):
        gate = self.gate_proj(x)
        up   = self.up_proj(x)
        hidden = F.silu(gate) * up
        return self.down_proj(hidden)


class TransformerBlock(nn.Module):
    def __init__(self, d_model, n_heads, d_k, intermediate):
        super().__init__()
        self.n_heads = n_heads
        self.d_k = d_k
        self.d_model = d_model

        self.attn_norm = nn.LayerNorm(d_model, elementwise_affine=True)
        self.ffn_norm  = nn.LayerNorm(d_model, elementwise_affine=True)

        self.q_proj   = nn.Linear(d_model, n_heads * d_k, bias=True)
        self.k_proj   = nn.Linear(d_model, n_heads * d_k, bias=True)
        self.v_proj   = nn.Linear(d_model, n_heads * d_k, bias=True)
        self.out_proj = nn.Linear(n_heads * d_k, d_model, bias=True)

        self.ffn = SwiGLUFFN(d_model, intermediate)

    def forward(self, x):
        residual = x
        h = self.attn_norm(x)

        Q = self.q_proj(h)
        K = self.k_proj(h)
        V = self.v_proj(h)

        B, N, _ = Q.shape
        Q = Q.view(B, N, self.n_heads, self.d_k).transpose(1, 2)
        K = K.view(B, N, self.n_heads, self.d_k).transpose(1, 2)
        V = V.view(B, N, self.n_heads, self.d_k).transpose(1, 2)

        scale = 1.0 / math.sqrt(self.d_k)
        scores = torch.matmul(Q, K.transpose(-2, -1)) * scale

        mask = torch.triu(torch.full((N, N), float('-inf'), device=x.device), diagonal=1)
        scores = scores + mask

        P = F.softmax(scores, dim=-1)
        attn_out = torch.matmul(P, V)

        attn_out = attn_out.transpose(1, 2).contiguous().view(B, N, -1)
        attn_out = self.out_proj(attn_out)
        x = residual + attn_out

        residual = x
        h = self.ffn_norm(x)
        h = self.ffn(h)
        x = residual + h
        return x


# ── Instantiate ──
block = TransformerBlock(d_model, n_heads, d_k, intermediate)
block.train()

x = torch.randn(B, N, d_model)
x.requires_grad_(True)

# ── Forward ──
out = block(x)

# ── Backward: sum loss ──
loss = out.sum()
loss.backward()

def fmt_tensor(name, t):
    flat = t.detach().cpu().numpy().flatten()
    vals = ', '.join(f'{v:.10f}f' for v in flat)
    return f'    float {name.replace(".","_")}[] = {{{vals}}};\n'

def fmt_shape(name, t):
    shape = list(t.shape)
    vals = ', '.join(str(s) for s in shape)
    return f'    int {name.replace(".","_")}_shape[] = {{{vals}}};\n\n'

# Group: list of (c_name, torch_tensor_or_grad_fn)
params_list = [
    ('x', x),
    ('output', out),
    ('grad_x', x.grad),
    ('grad_attn_norm_weight', block.attn_norm.weight.grad),
    ('grad_attn_norm_bias', block.attn_norm.bias.grad),
    ('grad_ffn_norm_weight', block.ffn_norm.weight.grad),
    ('grad_ffn_norm_bias', block.ffn_norm.bias.grad),
    ('grad_q_proj_weight', block.q_proj.weight.grad),
    ('grad_q_proj_bias', block.q_proj.bias.grad),
    ('grad_k_proj_weight', block.k_proj.weight.grad),
    ('grad_k_proj_bias', block.k_proj.bias.grad),
    ('grad_v_proj_weight', block.v_proj.weight.grad),
    ('grad_v_proj_bias', block.v_proj.bias.grad),
    ('grad_out_proj_weight', block.out_proj.weight.grad),
    ('grad_out_proj_bias', block.out_proj.bias.grad),
    ('grad_gate_proj_weight', block.ffn.gate_proj.weight.grad),
    ('grad_gate_proj_bias', block.ffn.gate_proj.bias.grad),
    ('grad_up_proj_weight', block.ffn.up_proj.weight.grad),
    ('grad_up_proj_bias', block.ffn.up_proj.bias.grad),
    ('grad_down_proj_weight', block.ffn.down_proj.weight.grad),
    ('grad_down_proj_bias', block.ffn.down_proj.bias.grad),
]

print("// Auto-generated by test/ref_transformer.py", file=sys.stderr)
print(f"// seed=42, config: B={B}, N={N}, d_model={d_model}, n_heads={n_heads}, d_k={d_k}, intermediate={intermediate}", file=sys.stderr)

print(f"/* Config: B={B}, N={N}, d_model={d_model}, n_heads={n_heads}, d_k={d_k}, intermediate={intermediate} */")
print()
for name, t in params_list:
    print(fmt_tensor(name, t))
    print()
